package learningTestNG;

public class Reportscanbegenerated {

	public static void main(String[] args) {  
		
		//Extent reports can be generated by using .xml file
		//jar
		//java program
		
		//copy the project home directory in the workspace
		 //extent-config.xml
		
		//add jar to the project build path in eclipse
		extentsreports-3.6 jar 
		
		
		
	}

}
